name: Docker
on:
  push:
    branches: [ master ]
  pull_request:
    branches:
      - master
jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    
    - name: Build and push Docker images for Solomon
      uses: docker/build-push-action@v1.1.0
      env:
        SHA8: ${{ GITHUB_SHA::8 }}  
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: satapps/terriamap
        dockerfile: ./deploy/docker-alternate/alternate.Dockerfile
        tags: $SHA8-solomon
        target: solomon_build
